name: Building the Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8  # Ensure flake8 is installed
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
        libvpx7 \
        libevent-2.1-7 \
        libopus0 \
        libgstreamer1.0-0 \
        libgstreamer-plugins-base1.0-0 \
        libharfbuzz-icu0 \
        libhyphen0 \
        libmanette-0.2-0 \
        libflite1 \
        libgles2 \
        woff2 \
        libgstreamer-gl1.0-0 \
        libgstreamer-plugins-bad1.0-0 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        playwright install
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8  # Ensure flake8 is installed
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        playwright install
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
