name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        playwright install
    - name: Run script and check output
      run: |
        python main.py  # Replace this command with your actual script execution command
        if [ -f Final.xlsx ]; then
          echo "Final.xlsx exists."
        else
          echo "Final.xlsx does not exist."
          exit 1  # This will fail the build if Final.xlsx is not found
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        playwright install
    - name: Run script and check output
      run: |
        python main.py  # Replace this command with your actual script execution command
        if [ -f Final.xlsx ]; then
          echo "Final.xlsx exists."
        else
          echo "Final.xlsx does not exist."
          exit 1  # This will fail the build if Final.xlsx is not found
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

